'use client'

import { safeClipboardWrite } from '@/lib/utils'
import { AnalysisResponse, PreviewData } from '../types'

interface CopywriterBriefProps {
  preview: PreviewData
  data: AnalysisResponse
  companyName: string
  hasCompetitorData: boolean
  onDownloadPDF: () => void
}

export function CopywriterBrief({
  preview,
  data,
  companyName,
  hasCompetitorData,
  onDownloadPDF,
}: CopywriterBriefProps) {
  const briefText = `# Website Messaging Brief for ${companyName}

## Overview
Messaging Differentiation Score: ${preview.commodityScore}/100
Pages Analyzed: ${preview.pagesScanned}
Date: ${new Date().toLocaleDateString()}

## Brand Voice Summary
${preview.voiceSummary ? `Current tone: ${preview.voiceSummary.currentTone}\nAuthentic voice: ${preview.voiceSummary.authenticVoice}` : 'See detailed findings below for voice patterns.'}

## Priority Fixes (Top 5)
${preview.topIssues.slice(0, 5).map((issue, i) => `${i + 1}. ${issue.title} (${issue.severity})\n   ${issue.description}`).join('\n\n')}

## Competitive Context
${hasCompetitorData && data?.competitorComparison?.detailedScores ? `Your score: ${data.competitorComparison.yourScore}/100\nCompetitors analyzed: ${data.competitorComparison.detailedScores.map((c) => c.url.replace(/^https?:\/\//, '').split('/')[0]).join(', ')}` : 'See competitor analysis section for positioning context.'}

## Key Messaging Rules
1. Lead with specific proof points (numbers, years, certifications)
2. Replace generic claims with specific outcomes
3. Name the ideal customer explicitly
4. Use active voice and direct CTAs

## Sample Rewrites
${preview.topIssues.slice(0, 3).flatMap((issue) => issue.findings?.slice(0, 1) || []).map((f) => `Before: "${f.phrase}"\nAfter: "${f.rewrite}"`).join('\n\n')}

---
Generated by Website Messaging Audit | leefuhr.com`

  return (
    <div className="mb-12">
      <div className="flex items-center justify-between mb-6">
        <h3 className="text-subsection">Copywriter brief</h3>
        <div className="flex gap-2">
          <button
            onClick={onDownloadPDF}
            className="text-sm bg-[var(--accent)] text-white px-4 py-2 font-semibold hover:opacity-90 transition-opacity"
          >
            Download PDF
          </button>
          <button
            onClick={async () => {
              const result = await safeClipboardWrite(briefText)
              const btn = document.getElementById('copy-brief-btn')
              if (btn) {
                btn.textContent = result.success ? 'Copied!' : 'Failed'
                setTimeout(() => {
                  btn.textContent = 'Copy'
                }, 2000)
              }
            }}
            id="copy-brief-btn"
            className="text-sm bg-gray-200 text-gray-700 px-4 py-2 font-semibold hover:bg-gray-300 transition-opacity"
          >
            Copy
          </button>
        </div>
      </div>
      <p className="text-body text-[var(--muted-foreground)] mb-4">
        A one-page summary you can hand to a copywriter or share with your team.
      </p>
      <div className="bg-gray-50 border-2 border-gray-200 rounded-lg p-6">
        <div className="grid md:grid-cols-2 gap-6">
          {[
            {
              label: 'Differentiation score',
              value: `${preview.commodityScore}/100`,
            },
            { label: 'Pages analyzed', value: String(preview.pagesScanned) },
            {
              label: 'Total rewrites',
              value: String(
                preview.topIssues.reduce((acc, issue) => acc + (issue.findings?.length || 0), 0),
              ),
            },
            {
              label: 'Critical issues',
              value: String(preview.topIssues.filter((i) => i.severity === 'critical').length),
            },
          ].map(({ label, value }) => (
            <div key={label}>
              <p className="text-xs text-[var(--muted-foreground)] uppercase tracking-wide mb-1">
                {label}
              </p>
              <p className="text-2xl font-bold">{value}</p>
            </div>
          ))}
        </div>
        <div className="mt-6 pt-6 border-t border-gray-200">
          <p className="text-xs text-[var(--muted-foreground)] uppercase tracking-wide mb-2">
            Top 3 priorities
          </p>
          <ol className="space-y-2">
            {preview.topIssues.slice(0, 3).map((issue, i) => (
              <li key={issue.title} className="flex items-start gap-2">
                <span className="text-[var(--accent)] font-bold">{i + 1}.</span>
                <span className="text-sm">{issue.title}</span>
              </li>
            ))}
          </ol>
        </div>
      </div>
    </div>
  )
}
